/*
 * stepper.h — step-pulse generation for both drivers.
 *
 *   DRV_TMC : the muxed TMC2209. Call Stepper_SelectMotor(0..7) first;
 *             that flips the 74HC595 so the TMC's coils reach one motor.
 *   DRV_TP  : the standalone TP6600 (dispense axis).
 *
 * Steps are generated by the channel's PWM (TIM2_CH1 / TIM3_CH4) and
 * counted in HAL_TIM_PWM_PulseFinishedCallback, so moves are non-blocking.
 *
 * REQUIREMENT (set in CubeMX): prescale TIM2 and TIM3 so the counter
 * ticks at 1 MHz (1 us). e.g. for a 100 MHz timer clock, PSC = 99.
 */
#ifndef STEPPER_H
#define STEPPER_H

#include <stdint.h>
#include <stdbool.h>

typedef enum { DRV_TMC = 0, DRV_TP = 1 } StepperDrv;

void Stepper_Init(void);
void Stepper_SelectMotor(uint8_t idx0);                 /* TMC mux, 0..7 */
void Stepper_Move(StepperDrv d, int32_t steps, uint32_t speed_hz);
void Stepper_Jog(StepperDrv d, bool forward, uint32_t speed_hz); /* run until Abort */
bool Stepper_Busy(StepperDrv d);
void Stepper_Abort(StepperDrv d);

/* Call from HAL_TIM_PWM_PulseFinishedCallback in your main.c. */
void Stepper_OnPulse(TIM_HandleTypeDef *htim);

#endif /* STEPPER_H */
